const browserGlobals = {
  AbortController: "readonly",
  CSS: "readonly",
  Document: "readonly",
  HTMLElement: "readonly",
  Image: "readonly",
  IntersectionObserver: "readonly",
  Node: "readonly",
  URL: "readonly",
  URLSearchParams: "readonly",
  addEventListener: "readonly",
  alert: "readonly",
  clearTimeout: "readonly",
  console: "readonly",
  document: "readonly",
  fetch: "readonly",
  globalThis: "readonly",
  history: "readonly",
  matchMedia: "readonly",
  navigator: "readonly",
  requestAnimationFrame: "readonly",
  setTimeout: "readonly",
  window: "readonly",
};

export default [
  {
    ignores: ["node_modules/**", "public/**", "playwright-report/**", "test-results/**", ".lighthouseci/**", "lhci_reports/**"],
  },
  {
    files: ["scripts/**/*.mjs", "src/js/**/*.js", "tests/**/*.mjs"],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: "module",
      globals: {
        ...browserGlobals,
        Buffer: "readonly",
        process: "readonly",
        setImmediate: "readonly",
      },
    },
    rules: {
      "array-callback-return": "error",
      "constructor-super": "error",
      eqeqeq: ["error", "always"],
      "no-constant-binary-expression": "error",
      "no-constant-condition": ["error", { checkLoops: false }],
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-dupe-else-if": "error",
      "no-duplicate-case": "error",
      "no-duplicate-imports": "error",
      "no-empty": "error",
      "no-fallthrough": "error",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-loss-of-precision": "error",
      "no-new-native-nonconstructor": "error",
      "no-obj-calls": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-sparse-arrays": "error",
      "no-unexpected-multiline": "error",
      "no-unreachable": "error",
      "no-unreachable-loop": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unused-vars": ["error", { args: "after-used", ignoreRestSiblings: true }],
      "no-useless-backreference": "error",
      "no-useless-catch": "error",
      "no-useless-escape": "error",
      "no-with": "error",
      "prefer-const": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
    },
  },
];
